"""LLM Runtime State Model — matches LLAMA_CPP_RUNTIME_ARCHITECTURE.md §4."""
from enum import Enum


class LLMRuntimeState(str, Enum):
    SERVER_STOPPED = "SERVER_STOPPED"
    SERVER_STARTING = "SERVER_STARTING"
    MODEL_UNLOADED = "MODEL_UNLOADED"
    MODEL_LOADING = "MODEL_LOADING"
    MODEL_READY = "MODEL_READY"
    MODEL_SLEEPING = "MODEL_SLEEPING"
    MODEL_UNLOADING = "MODEL_UNLOADING"
    MODEL_ERROR = "MODEL_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
